import type { Message } from './types';

export const MOCK_MESSAGES: Message[] = [
  {
    id: 1,
    sender: 'Alice Johnson',
    subject: 'Project Phoenix Deadline',
    body: `Hi team, please remember that the deadline for Project Phoenix is this Friday. I need all final reports submitted by 5 PM. This is critical for our Q3 review. Let me know if you foresee any issues. We need to present this to the board next week, so there's no room for delays. Thanks, Alice`,
    timestamp: '10:45 AM',
    channel: 'Business',
    avatar: 'https://picsum.photos/seed/1/40/40',
    read: false,
    replies: [],
  },
  {
    id: 2,
    sender: 'Mom',
    subject: 'Dinner on Saturday?',
    body: `Hey sweetie, hope you're having a good week! Your dad and I were wondering if you'd be free to come over for dinner this Saturday. We could make your favorite lasagna. Let us know if you can make it. Love, Mom`,
    timestamp: '9:30 AM',
    channel: 'Personal',
    avatar: 'https://picsum.photos/seed/2/40/40',
    read: true,
    replies: [],
  },
  {
    id: 3,
    sender: 'David Chen - Acme Corp',
    subject: 'Re: Invoice #12345',
    body: `Hello, following up on invoice #12345. Our records show it is now 15 days past due. Please remit payment at your earliest convenience to avoid service interruption. If you've already paid, please disregard this message. Regards, David Chen, Accounts Receivable, Acme Corp.`,
    timestamp: 'Yesterday',
    channel: 'Business',
    avatar: 'https://picsum.photos/seed/3/40/40',
    read: false,
    replies: [],
  },
  {
    id: 4,
    sender: 'Sarah Miller',
    subject: 'Weekend trip ideas',
    body: `Hey! I was thinking we should plan a weekend getaway soon. Maybe hiking up north or a beach trip? I found a couple of cool Airbnbs. Let's chat this week and figure something out!`,
    timestamp: 'Yesterday',
    channel: 'Personal',
    avatar: 'https://picsum.photos/seed/4/40/40',
    read: true,
    replies: [],
  },
  {
    id: 5,
    sender: 'Tech Weekly Newsletter',
    subject: 'The Future of AI and You',
    body: `This week in tech: Quantum computing takes a leap forward, a new framework challenges React, and we explore how generative AI is changing the landscape of software development. Plus, get our top 5 productivity apps for 2024.`,
    timestamp: '2 days ago',
    channel: 'Business',
    avatar: 'https://picsum.photos/seed/5/40/40',
    read: true,
    replies: [],
  },
  {
    id: 6,
    sender: 'Dr. Evans Office',
    subject: 'Your appointment is confirmed',
    body: `This is a reminder of your appointment with Dr. Evans on October 28th at 2:00 PM. Please arrive 15 minutes early to complete any necessary paperwork.`,
    timestamp: '3 days ago',
    channel: 'Personal',
    avatar: 'https://picsum.photos/seed/6/40/40',
    read: true,
    replies: [],
  },
   {
    id: 7,
    sender: 'HR Department',
    subject: 'URGENT: Action Required - Annual Compliance Training',
    body: 'This is a mandatory reminder that all employees must complete the annual compliance and security training by the end of the month. Failure to do so will result in temporary suspension of network access. Please log in to the employee portal to complete the modules immediately. Thank you for your cooperation.',
    timestamp: '4 days ago',
    channel: 'Business',
    avatar: 'https://picsum.photos/seed/7/40/40',
    read: false,
    replies: [],
  },
];